CREATE TABLE seguimiento_correos
(
    ID_SEGUIMIENTO_CORREO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DOCUMENTO VARCHAR(25) NOT NULL,
    CORREO TEXT NOT NULL,
    DIPLOMADO TEXT NOT NULL,
    CENTRO VARCHAR(50) NOT NULL,
    TIPO_CORREO VARCHAR(50) NOT NULL,
    FECHA_CORREO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);